# Generated by Django 2.2.6 on 2019-12-11 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_ad', models.CharField(max_length=20, null=True)),
                ('length', models.DateTimeField()),
                ('reason', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_count', models.IntegerField()),
                ('post_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_pos', models.IntegerField(default=1)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('op_email', models.CharField(blank=True, max_length=20, null=True)),
                ('thread_title', models.CharField(blank=True, max_length=20, null=True)),
                ('thread_body', models.TextField()),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chanImgs/')),
                ('rep', models.BooleanField(blank=True, default=True)),
                ('rep_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('banned', models.BooleanField(blank=True, default=True)),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rep_res', models.CharField(blank=True, default='No reason provided', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('op_email', models.CharField(blank=True, max_length=20, null=True)),
                ('answer_title', models.CharField(blank=True, max_length=20, null=True)),
                ('answer_body', models.TextField()),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chanImgs/')),
                ('rep', models.BooleanField(blank=True, default=True)),
                ('rep_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('banned', models.BooleanField(blank=True, default=True)),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rep_res', models.CharField(blank=True, default='No reason provided', max_length=200, null=True)),
                ('Thread', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_ans', to='obiadekchan.Thread')),
            ],
        ),
    ]
