# Generated by Django 2.2.9 on 2020-01-04 06:02

from django.db import migrations, models
import obiadekchan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_ad', models.CharField(max_length=20, null=True)),
                ('length', models.DateTimeField()),
                ('reason', models.CharField(max_length=100, null=True)),
                ('post_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_pos', models.IntegerField(default=1)),
                ('op_email', models.CharField(blank=True, max_length=20, null=True)),
                ('post_title', models.CharField(blank=True, max_length=20, null=True)),
                ('post_body', models.TextField()),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('image', models.ImageField(blank=True, null=True, upload_to=obiadekchan.models.file_name)),
                ('rep', models.BooleanField(blank=True, default=True)),
                ('rep_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('banned', models.BooleanField(blank=True, default=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('rep_res', models.CharField(blank=True, default='No reason provided', max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('is_thread', models.BooleanField()),
                ('is_op', models.BooleanField(blank=True, null=True)),
                ('is_mode', models.BooleanField(blank=True, null=True)),
                ('replies', models.ManyToManyField(blank=True, related_name='_post_replies_+', to='obiadekchan.Post')),
            ],
        ),
    ]
