# Generated by Django 2.2.6 on 2019-11-25 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_pos', models.IntegerField(default=1)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('op_email', models.CharField(max_length=20, null=True)),
                ('thread_title', models.CharField(max_length=20, null=True)),
                ('thread_body', models.TextField()),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='chanImgs/')),
                ('rep', models.BooleanField(blank=True, default=False)),
                ('rep_reason', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('op_email', models.CharField(max_length=20, null=True)),
                ('answer_title', models.CharField(max_length=20, null=True)),
                ('answer_body', models.TextField()),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='chanImgs/')),
                ('rep', models.BooleanField(blank=True, default=False)),
                ('rep_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('Thread', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_ans', to='obiadekchan.Thread')),
            ],
        ),
    ]
