# Generated by Django 2.2.6 on 2019-11-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obiadekchan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rep',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='rep',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
